---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stderr

    sentry:
        class: raven.handlers.logging.SentryHandler
        level: WARN
        formatter: simple

loggers:
    requests.packages.urllib3.connectionpool:
        level: WARNING
        handlers: [console, sentry]
        propagate: no

root:
    level: INFO
    handlers: [console, sentry]
...